/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { anyApi } from "convex/server";
import { mutation } from "convex/server";
import { query } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api = anyApi;
export const internal = anyApi;

export const updateUserPoints = mutation(async ({ db }, { tgUserId, points }) => {
  await db.table("users").update(tgUserId, { points });
});

export const userByTelegramId = query(async ({ db }, { tgUserId }) => {
  return await db.table("users").filter(q => q.eq("tgUserId", tgUserId)).first();
});